# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Elexol-EtherIO24
version:      0.17
version_from: lib/Net/Elexol/EtherIO24.pm
installdirs:  site
requires:
    IO::Select:                    0
    IO::Socket::INET:              0
    Socket:                        0
    Test::More:                    0
    threads:                       0
    threads::shared:               0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
